version: '3'

services:
    # MySQL
    db:
        # 2020/1/13リリースバージョン
        image: mysql:8.0.19
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        # ローカルからDBにアクセスする場合
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: sample_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: beeeeyan
            MYSQL_PASSWORD: test
            TZ: 'Asia/Tokyo'
        volumes:
          # 永続化したい場合
          # - ./db/data:/var/lib/mysql
          - ./db/initdb:/docker-entrypoint-initdb.d
        ports:
          - 33306:3306
        container_name: sample_db